# Generated by Django 4.2.14 on 2024-08-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la especialidad', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la especialidad', max_length=50, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
    ]
