# Generated by Django 4.2.13 on 2024-06-28 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_alter_usuario_ciudad_alter_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
