# Generated by Django 4.2.14 on 2024-09-13 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionmedica', '0002_medico'),
        ('catalogos', '0002_examen_medicamento_alter_diagnostico_codigo_and_more'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=5)),
                ('motivo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.diagnostico')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmedica.especialidad')),
                ('examenes', models.ManyToManyField(blank=True, to='catalogos.examen')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmedica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Citas Médicas',
                'unique_together': {('hora', 'medico', 'paciente')},
            },
        ),
    ]
