# Generated by Django 4.2.13 on 2024-06-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_rename_staff_usuario_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='estado',
            new_name='is_active',
        ),
    ]
